### ISSUE TITLE
[BUG] No notifications on LineageOS

### ISSUE THREAD

**Issue by 3Lord3** [FriesI23/mhabit#135]
## Before reporting bug, make sure the following options

- [X] Check for the Latest Version [HERE](https://github.com/FriesI23/mhabit/releases/latest)
- [X] Search for Existing Issues [HERE](https://github.com/FriesI23/mhabit/issues?q=is%3Aissue)
- [x] Verify if this BUG can be reproduced

---

**Description**
I'm not receiving notifications from the app

**Step to Reproduce**
1. Install LineageOS
2. Install Table Habit app
3. Allow notifications
4. Set a notification
5. Wait until the notification should be arrives

**Expected Behavior**
Normal notifications behavior

**Device/Environment Info**
OnePlus 6T, Android 13, LineageOS 20-202440116-NIGHTLY-fajita
Latest app version

**Additional Context**
I don't have Google Play Services
Notifications do not arrive either in the app, outside the app, or on the locked screen
Previously, on OxygenOS with Android 11 everything worked

**Comment by Miaaaim** [comment]
duplicate #118

Thanks for your suggestion.

**Comment by FriesI23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [not raise reminders](https://trello.com/c/PjNZEEB4/66-not-raise-reminders)

**Comment by 3Lord3** [comment]
There is stll no notifications after last update

**Comment by FriesI23** [comment]
Sorry, I don't have any device compatible with LineageOS, and it seems that there are no emulator options available currently. 
So... this issue maybe addressed at a later time (when I obtain a compatible device and reproduce this bug).

**Comment by stevennic22** [comment]
I was a commenter on #118, and am also still experiencing this issue. My device (Pixel 5a) isn't on LineageOS, instead I'm on the Android 14 from Google directly.

I am able to test but I don't have a way to patch and build locally.

**Comment by FriesI23** [comment]
found problem and workaround [here](https://github.com/MaikuB/flutter_local_notifications/issues/2223#issuecomment-1925452782)

i will fix it in next release.

**Comment by FriesI23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BUG] Crash after boot](https://trello.com/c/Ve8iM7lz/68-bug-crash-after-boot)
